name: sk-ex-model-inference
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas=1.4.4
  - numpy=1.21.5
  - scikit-learn=1.1.1
  - pip:
    - fastapi==0.87.0
    - uvicorn=0.19.0
    - mlflow==1.29.0
    - pytest==7.1.3
    - pyarrow==10.0.0