name: sk-ex-model
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas=1.4.4
  - numpy=1.21.5
  - scikit-learn=1.1.1
  - pip:
    - mlflow==1.29.0
    - pytest==7.1.3
    - seaborn==0.12.0
    - matplotlib==3.6.0
    - pyarrow==10.0.0
